# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(1124, 631)
        self.centralwidget = QtWidgets.QWidget(Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.ExtractStempels = QtWidgets.QPushButton(self.centralwidget)
        self.ExtractStempels.setGeometry(QtCore.QRect(10, 540, 251, 41))
        self.ExtractStempels.setObjectName("ExtractStempels")
        self.SearchFile = QtWidgets.QPushButton(self.centralwidget)
        self.SearchFile.setGeometry(QtCore.QRect(10, 440, 251, 41))
        self.SearchFile.setObjectName("SearchFile")
        self.SelectedFile = QtWidgets.QLineEdit(self.centralwidget)
        self.SelectedFile.setGeometry(QtCore.QRect(270, 440, 271, 41))
        self.SelectedFile.setReadOnly(True)
        self.SelectedFile.setObjectName("SelectedFile")
        self.ProcessFile = QtWidgets.QPushButton(self.centralwidget)
        self.ProcessFile.setGeometry(QtCore.QRect(10, 490, 251, 41))
        self.ProcessFile.setCheckable(False)
        self.ProcessFile.setFlat(False)
        self.ProcessFile.setObjectName("ProcessFile")
        self.TableLists = QtWidgets.QComboBox(self.centralwidget)
        self.TableLists.setGeometry(QtCore.QRect(10, 10, 531, 22))
        self.TableLists.setObjectName("TableLists")
        self.TableData = QtWidgets.QTableWidget(self.centralwidget)
        self.TableData.setGeometry(QtCore.QRect(10, 40, 531, 391))
        self.TableData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableData.setObjectName("TableData")
        self.TableData.setColumnCount(0)
        self.TableData.setRowCount(0)
        self.Graph = MPlwidget(self.centralwidget)
        self.Graph.setGeometry(QtCore.QRect(549, 9, 581, 421))
        self.Graph.setObjectName("Graph")
        self.ExportStempels = QtWidgets.QPushButton(self.centralwidget)
        self.ExportStempels.setGeometry(QtCore.QRect(270, 540, 271, 41))
        self.ExportStempels.setObjectName("ExportStempels")
        self.ExtractWalls = QtWidgets.QPushButton(self.centralwidget)
        self.ExtractWalls.setGeometry(QtCore.QRect(270, 490, 271, 41))
        self.ExtractWalls.setObjectName("ExtractWalls")
        self.GordingUnityCheck = QtWidgets.QPushButton(self.centralwidget)
        self.GordingUnityCheck.setGeometry(QtCore.QRect(550, 440, 261, 41))
        self.GordingUnityCheck.setObjectName("GordingUnityCheck")
        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        Interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Interface)
        self.statusbar.setObjectName("statusbar")
        Interface.setStatusBar(self.statusbar)

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "MainWindow"))
        self.ExtractStempels.setText(_translate("Interface", "Extract stempels"))
        self.SearchFile.setText(_translate("Interface", "Search file"))
        self.SelectedFile.setPlaceholderText(_translate("Interface", "Filename"))
        self.ProcessFile.setText(_translate("Interface", "Process file"))
        self.ExportStempels.setText(_translate("Interface", "Export stempels"))
        self.ExtractWalls.setText(_translate("Interface", "Extract walls"))
        self.GordingUnityCheck.setText(_translate("Interface", "Gording unity check"))
from mplwidget import MPlwidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interface = QtWidgets.QMainWindow()
    ui = Ui_Interface()
    ui.setupUi(Interface)
    Interface.show()
    sys.exit(app.exec_())
