# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Popup(object):
    def setupUi(self, Popup):
        Popup.setObjectName("Popup")
        Popup.resize(388, 177)
        self.SearchFile = QtWidgets.QPushButton(Popup)
        self.SearchFile.setGeometry(QtCore.QRect(10, 10, 88, 34))
        self.SearchFile.setObjectName("SearchFile")
        self.FileLocation = QtWidgets.QLabel(Popup)
        self.FileLocation.setGeometry(QtCore.QRect(120, 20, 241, 18))
        self.FileLocation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FileLocation.setObjectName("FileLocation")
        self.FileName = QtWidgets.QLineEdit(Popup)
        self.FileName.setGeometry(QtCore.QRect(10, 60, 371, 32))
        self.FileName.setObjectName("FileName")
        self.Save = QtWidgets.QPushButton(Popup)
        self.Save.setGeometry(QtCore.QRect(20, 120, 88, 34))
        self.Save.setObjectName("Save")
        self.pushButton = QtWidgets.QPushButton(Popup)
        self.pushButton.setGeometry(QtCore.QRect(280, 120, 88, 34))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Popup)
        QtCore.QMetaObject.connectSlotsByName(Popup)

    def retranslateUi(self, Popup):
        _translate = QtCore.QCoreApplication.translate
        Popup.setWindowTitle(_translate("Popup", "Form"))
        self.SearchFile.setText(_translate("Popup", "Save to"))
        self.FileLocation.setText(_translate("Popup", "No file selected"))
        self.FileName.setText(_translate("Popup", "File_name"))
        self.Save.setText(_translate("Popup", "Save"))
        self.pushButton.setText(_translate("Popup", "Cancel"))
