from munch import Munch

H22_0225_B_Stempelframe2_params = Munch({
    'project_general': Munch({
        'basics': Munch({
            'name_client': '',
            'name_number': '',
            'name_engineer': '',
            'name_project': '',
            'name_location': '',
            'date': '',
            'name_layer': '',
            'name_attentoins': ''})}),
    'general': Munch({
        'geometry': Munch({
            'nodes': [Munch({
                'id': '1',
                'x': 0.419,
                'z': 14.554}), Munch({
                'id': '2',
                'x': 3.068,
                'z': 13.489}),
                Munch({
                    'id': '3',
                    'x': 4.417,
                    'z': 13.114}), Munch({
                    'id': '4',
                    'x': 9.598302,
                    'z': 11.693802}),
                Munch({
                    'id': '5',
                    'x': 16.599493,
                    'z': 9.698165}), Munch({
                    'id': '6',
                    'x': 23.89514,
                    'z': 7.682255}),
                Munch({
                    'id': '7',
                    'x': 31.800001,
                    'z': 5.5}), Munch({
                    'id': '8',
                    'x': 37.995335,
                    'z': 3.783319}),
                Munch({
                    'id': '9',
                    'x': 43.299999,
                    'z': 2.3}), Munch({
                    'id': '10',
                    'x': 48.29837,
                    'z': 0.894207}),
                Munch({
                    'id': '11',
                    'x': 51.62,
                    'z': 0}), Munch({
                    'id': '12',
                    'x': 54.598,
                    'z': 0.448}),
                Munch({
                    'id': '13',
                    'x': 59.542,
                    'z': 1.191}), Munch({
                    'id': '14',
                    'x': 59.542,
                    'z': 5.191}),
                Munch({
                    'id': '15',
                    'x': 59.542,
                    'z': 10.191}), Munch({
                    'id': '16',
                    'x': 59.542,
                    'z': 16.191}),
                Munch({
                    'id': '17',
                    'x': 59.542,
                    'z': 19.411}), Munch({
                    'id': '18',
                    'x': 60.203,
                    'z': 19.411}),
                Munch({
                    'id': '19',
                    'x': 62.202,
                    'z': 19.411}), Munch({
                    'id': '20',
                    'x': 62.202,
                    'z': 21.911}),
                Munch({
                    'id': '21',
                    'x': 62.202,
                    'z': 25.399}), Munch({
                    'id': '22',
                    'x': 62.202,
                    'z': 33.243}),
                Munch({
                    'id': '23',
                    'x': 62.202,
                    'z': 39.399}), Munch({
                    'id': '24',
                    'x': 62.202,
                    'z': 44.399}),
                Munch({
                    'id': '25',
                    'x': 62.202,
                    'z': 49.399}), Munch({
                    'id': '26',
                    'x': 62.202,
                    'z': 54.399}),
                Munch({
                    'id': '27',
                    'x': 62.202,
                    'z': 59.399}), Munch({
                    'id': '28',
                    'x': 57.202,
                    'z': 59.399}),
                Munch({
                    'id': '29',
                    'x': 52.202,
                    'z': 59.399}), Munch({
                    'id': '30',
                    'x': 47.202,
                    'z': 59.399}),
                Munch({
                    'id': '31',
                    'x': 41.793,
                    'z': 59.399}), Munch({
                    'id': '32',
                    'x': 36.793,
                    'z': 59.399}),
                Munch({
                    'id': '33',
                    'x': 31.793,
                    'z': 59.399}), Munch({
                    'id': '34',
                    'x': 26.792,
                    'z': 59.399}),
                Munch({
                    'id': '35',
                    'x': 26.71,
                    'z': 54.316}), Munch({
                    'id': '36',
                    'x': 26.622,
                    'z': 49.228}),
                Munch({
                    'id': '37',
                    'x': 26.534,
                    'z': 44.14}), Munch({
                    'id': '38',
                    'x': 26.451,
                    'z': 39.399}),
                Munch({
                    'id': '39',
                    'x': 26.364,
                    'z': 34.399}), Munch({
                    'id': '40',
                    'x': 26.344,
                    'z': 33.243}),
                Munch({
                    'id': '41',
                    'x': 21.600328,
                    'z': 34.101925}), Munch({
                    'id': '42',
                    'x': 17.305687,
                    'z': 34.832043}),
                Munch({
                    'id': '43',
                    'x': 13.186,
                    'z': 35.563}), Munch({
                    'id': '44',
                    'x': 8.262,
                    'z': 36.431}),
                Munch({
                    'id': '45',
                    'x': 3.338,
                    'z': 37.299}), Munch({
                    'id': '46',
                    'x': 2.47,
                    'z': 32.375}),
                Munch({
                    'id': '47',
                    'x': 2.192,
                    'z': 30.8}), Munch({
                    'id': '48',
                    'x': 1.485,
                    'z': 28.691}),
                Munch({
                    'id': '49',
                    'x': 1.219,
                    'z': 27.184}), Munch({
                    'id': '50',
                    'x': 0.748,
                    'z': 24.513}),
                Munch({
                    'id': '51',
                    'x': 0.511,
                    'z': 23.17}), Munch({
                    'id': '52',
                    'x': 0.563,
                    'z': 20.928}),
                Munch({
                    'id': '53',
                    'x': 0.177,
                    'z': 18.741}), Munch({
                    'id': '54',
                    'x': 0,
                    'z': 17.736})]}),
        'beams': Munch({
            'staven': [Munch({
                'id': '1',
                'ki': '1',
                'kj': '2',
                'profiel': 'HEB500',
                'strength_class': 'S235',
                'aansli': 'ND',
                'aanslj': 'NDM',
                'hoh': '2.855'}), Munch({
                'id': '2',
                'ki': '2',
                'kj': '3',
                'profiel': 'HEB500',
                'strength_class': 'S235',
                'aansli': 'NDM',
                'aanslj': 'NDM',
                'hoh': '1.4'}),
                Munch({
                    'id': '3',
                    'ki': '3',
                    'kj': '4',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.372'}), Munch({
                    'id': '4',
                    'ki': '4',
                    'kj': '5',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '7.28'}),
                Munch({
                    'id': '5',
                    'ki': '5',
                    'kj': '6',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '7.569'}), Munch({
                    'id': '6',
                    'ki': '6',
                    'kj': '7',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '8.201'}),
                Munch({
                    'id': '7',
                    'ki': '7',
                    'kj': '8',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '6.429'}), Munch({
                    'id': '8',
                    'ki': '8',
                    'kj': '9',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.508'}),
                Munch({
                    'id': '9',
                    'ki': '9',
                    'kj': '10',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.192'}), Munch({
                    'id': '10',
                    'ki': '10',
                    'kj': '11',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '3.44'}),
                Munch({
                    'id': '11',
                    'ki': '11',
                    'kj': '12',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '3.012'}), Munch({
                    'id': '12',
                    'ki': '12',
                    'kj': '13',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '13',
                    'ki': '13',
                    'kj': '14',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'ND',
                    'aanslj': 'NDM',
                    'hoh': '4.0'}), Munch({
                    'id': '14',
                    'ki': '14',
                    'kj': '15',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '15',
                    'ki': '15',
                    'kj': '16',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '6.0'}), Munch({
                    'id': '16',
                    'ki': '16',
                    'kj': '17',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'ND',
                    'hoh': '3.22'}),
                Munch({
                    'id': '17',
                    'ki': '17',
                    'kj': '18',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '0.661'}), Munch({
                    'id': '18',
                    'ki': '18',
                    'kj': '19',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.999'}),
                Munch({
                    'id': '19',
                    'ki': '19',
                    'kj': '20',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'ND',
                    'aanslj': 'NDM',
                    'hoh': '2.5'}), Munch({
                    'id': '20',
                    'ki': '20',
                    'kj': '21',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '3.488'}),
                Munch({
                    'id': '21',
                    'ki': '21',
                    'kj': '22',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '7.844'}), Munch({
                    'id': '22',
                    'ki': '22',
                    'kj': '23',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '6.156'}),
                Munch({
                    'id': '23',
                    'ki': '23',
                    'kj': '24',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '24',
                    'ki': '24',
                    'kj': '25',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '25',
                    'ki': '25',
                    'kj': '26',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '26',
                    'ki': '26',
                    'kj': '27',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '27',
                    'ki': '27',
                    'kj': '28',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'ND',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '28',
                    'ki': '28',
                    'kj': '29',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '29',
                    'ki': '29',
                    'kj': '30',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '30',
                    'ki': '30',
                    'kj': '31',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.409'}),
                Munch({
                    'id': '31',
                    'ki': '31',
                    'kj': '32',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '32',
                    'ki': '32',
                    'kj': '33',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '33',
                    'ki': '33',
                    'kj': '34',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.001'}), Munch({
                    'id': '34',
                    'ki': '34',
                    'kj': '35',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'ND',
                    'aanslj': 'NDM',
                    'hoh': '5.084'}),
                Munch({
                    'id': '35',
                    'ki': '35',
                    'kj': '36',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.089'}), Munch({
                    'id': '36',
                    'ki': '36',
                    'kj': '37',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.089'}),
                Munch({
                    'id': '37',
                    'ki': '37',
                    'kj': '38',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '4.742'}), Munch({
                    'id': '38',
                    'ki': '38',
                    'kj': '39',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.001'}),
                Munch({
                    'id': '39',
                    'ki': '39',
                    'kj': '40',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.156'}), Munch({
                    'id': '40',
                    'ki': '40',
                    'kj': '41',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '4.821'}),
                Munch({
                    'id': '41',
                    'ki': '41',
                    'kj': '42',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '4.356'}), Munch({
                    'id': '42',
                    'ki': '42',
                    'kj': '43',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '4.184'}),
                Munch({
                    'id': '43',
                    'ki': '43',
                    'kj': '44',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '44',
                    'ki': '44',
                    'kj': '45',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}),
                Munch({
                    'id': '45',
                    'ki': '45',
                    'kj': '46',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'ND',
                    'aanslj': 'NDM',
                    'hoh': '5.0'}), Munch({
                    'id': '46',
                    'ki': '46',
                    'kj': '47',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.599'}),
                Munch({
                    'id': '47',
                    'ki': '47',
                    'kj': '48',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '2.224'}), Munch({
                    'id': '48',
                    'ki': '48',
                    'kj': '49',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.53'}),
                Munch({
                    'id': '49',
                    'ki': '49',
                    'kj': '50',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '2.712'}), Munch({
                    'id': '50',
                    'ki': '50',
                    'kj': '51',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.364'}),
                Munch({
                    'id': '51',
                    'ki': '51',
                    'kj': '52',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '2.243'}), Munch({
                    'id': '52',
                    'ki': '52',
                    'kj': '53',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '2.221'}),
                Munch({
                    'id': '53',
                    'ki': '53',
                    'kj': '54',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '1.02'}), Munch({
                    'id': '54',
                    'ki': '54',
                    'kj': '1',
                    'profiel': 'HEB500',
                    'strength_class': 'S235',
                    'aansli': 'NDM',
                    'aanslj': 'NDM',
                    'hoh': '3.209'}),
                Munch({
                    'id': '55',
                    'ki': '53',
                    'kj': '3',
                    'profiel': 'B406/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '7.046'}), Munch({
                    'id': '56',
                    'ki': '12',
                    'kj': '14',
                    'profiel': 'B406/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '6.851'}),
                Munch({
                    'id': '57',
                    'ki': '18',
                    'kj': '20',
                    'profiel': 'B406/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '3.201'}), Munch({
                    'id': '58',
                    'ki': '26',
                    'kj': '28',
                    'profiel': 'B508/12.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '7.071'}),
                Munch({
                    'id': '59',
                    'ki': '33',
                    'kj': '35',
                    'profiel': 'B508/12.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '7.188'}), Munch({
                    'id': '60',
                    'ki': '44',
                    'kj': '46',
                    'profiel': 'B508/12.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '7.071'}),
                Munch({
                    'id': '61',
                    'ki': '50',
                    'kj': '4',
                    'profiel': 'B457/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '15.578'}), Munch({
                    'id': '62',
                    'ki': '10',
                    'kj': '15',
                    'profiel': 'B457/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '14.589'}),
                Munch({
                    'id': '63',
                    'ki': '25',
                    'kj': '29',
                    'profiel': 'B610/14.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '14.142'}), Munch({
                    'id': '64',
                    'ki': '32',
                    'kj': '36',
                    'profiel': 'B610/14.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '14.384'}),
                Munch({
                    'id': '65',
                    'ki': '43',
                    'kj': '49',
                    'profiel': 'B457/10',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '14.609'}), Munch({
                    'id': '66',
                    'ki': '9',
                    'kj': '16',
                    'profiel': 'B610/14.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '21.372'}),
                Munch({
                    'id': '67',
                    'ki': '24',
                    'kj': '30',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '21.213'}), Munch({
                    'id': '68',
                    'ki': '31',
                    'kj': '37',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '21.579'}),
                Munch({
                    'id': '69',
                    'ki': '42',
                    'kj': '5',
                    'profiel': 'B610/14.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '25.144'}), Munch({
                    'id': '70',
                    'ki': '41',
                    'kj': '6',
                    'profiel': 'B610/14.5',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '26.519'}),
                Munch({
                    'id': '71',
                    'ki': '40',
                    'kj': '7',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '28.274'}), Munch({
                    'id': '72',
                    'ki': '8',
                    'kj': '21',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '32.453'}),
                Munch({
                    'id': '73',
                    'ki': '40',
                    'kj': '22',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '35.858'}), Munch({
                    'id': '74',
                    'ki': '38',
                    'kj': '23',
                    'profiel': 'B762/16',
                    'strength_class': 'S355',
                    'aansli': 'ND',
                    'aanslj': 'ND',
                    'hoh': '35.751'})]}),
        'bedding': Munch({
            'staven': [Munch({
                'ID': '1',
                'BarID': '1-54',
                'BeddingValue': '2500.',
                'BeddingWidth': '1.',
                'Side': 'Negative'}), Munch({
                'ID': '',
                'BarID': '',
                'BeddingValue': '',
                'BeddingWidth': '',
                'Side': None})]}),
        'FixedSupports': Munch({
            'nodes': []}),
        'SpringSupports': Munch({
            'nodes': [Munch({
                'ID': '1',
                'NodeID': '6',
                'Direction': 'X',
                'SpringConstant': '28000.',
                'SpringType': 'Normal',
                'LowerLimit': '-560.',
                'UpperLimit': '560.',
                'support_lsc_angle': 15.53}),
                Munch({
                    'ID': '2',
                    'NodeID': '7',
                    'Direction': 'X',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 15.53}),
                Munch({
                    'ID': '3',
                    'NodeID': '14',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '4',
                    'NodeID': '15',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '5',
                    'NodeID': '16',
                    'Direction': 'Z',
                    'SpringConstant': '35000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-700.',
                    'UpperLimit': '700.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '6',
                    'NodeID': '18',
                    'Direction': 'X',
                    'SpringConstant': '14000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-280.',
                    'UpperLimit': '280.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '7',
                    'NodeID': '24',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '8',
                    'NodeID': '25',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 0}),
                Munch({
                    'ID': '9',
                    'NodeID': '36',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 1}),
                Munch({
                    'ID': '10',
                    'NodeID': '37',
                    'Direction': 'Z',
                    'SpringConstant': '28000.',
                    'SpringType': 'Normal',
                    'LowerLimit': '-560.',
                    'UpperLimit': '560.',
                    'support_lsc_angle': 1})]}),
        'BarLoad_UGT': Munch({
            'staven': [Munch({
                'ID': '1',
                'BarID': '1',
                'Type': 'QZL',
                'LoadStart': '85.',
                'LoadEnd': '85.',
                'DistanceStart': '0.',
                'DistanceEnd': '0.'}), Munch({
                'ID': '2',
                'BarID': '2',
                'Type': 'QZL',
                'LoadStart': '85.',
                'LoadEnd': '85.',
                'DistanceStart': '0.',
                'DistanceEnd': '0.'}),
                Munch({
                    'ID': '3',
                    'BarID': '3',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '4',
                    'BarID': '4',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '5',
                    'BarID': '5',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '6',
                    'BarID': '6',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '7',
                    'BarID': '7',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '8',
                    'BarID': '8',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '9',
                    'BarID': '9',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '10',
                    'BarID': '10',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '11',
                    'BarID': '11',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '12',
                    'BarID': '12',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '13',
                    'BarID': '13',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '14',
                    'BarID': '14',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '15',
                    'BarID': '15',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '16',
                    'BarID': '16',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '17',
                    'BarID': '17',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '18',
                    'BarID': '18',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '19',
                    'BarID': '19',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '20',
                    'BarID': '20',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '21',
                    'BarID': '21',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '22',
                    'BarID': '22',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '23',
                    'BarID': '23',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '24',
                    'BarID': '24',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '25',
                    'BarID': '25',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '26',
                    'BarID': '26',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '27',
                    'BarID': '27',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '28',
                    'BarID': '28',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '29',
                    'BarID': '29',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '30',
                    'BarID': '30',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '31',
                    'BarID': '31',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '32',
                    'BarID': '32',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '33',
                    'BarID': '33',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '34',
                    'BarID': '34',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '35',
                    'BarID': '35',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '36',
                    'BarID': '36',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '37',
                    'BarID': '37',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '38',
                    'BarID': '38',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '39',
                    'BarID': '39',
                    'Type': 'QZL',
                    'LoadStart': '85.',
                    'LoadEnd': '85.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '40',
                    'BarID': '40',
                    'Type': 'QZL',
                    'LoadStart': '106.',
                    'LoadEnd': '106.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '41',
                    'BarID': '41',
                    'Type': 'QZL',
                    'LoadStart': '106.',
                    'LoadEnd': '106.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '42',
                    'BarID': '42',
                    'Type': 'QZL',
                    'LoadStart': '106.',
                    'LoadEnd': '106.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '43',
                    'BarID': '43',
                    'Type': 'QZL',
                    'LoadStart': '106.',
                    'LoadEnd': '106.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '44',
                    'BarID': '44',
                    'Type': 'QZL',
                    'LoadStart': '106.',
                    'LoadEnd': '106.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '45',
                    'BarID': '45',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '46',
                    'BarID': '46',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '47',
                    'BarID': '47',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '48',
                    'BarID': '48',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '49',
                    'BarID': '49',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '50',
                    'BarID': '50',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '51',
                    'BarID': '51',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '52',
                    'BarID': '52',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '53',
                    'BarID': '53',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '54',
                    'BarID': '54',
                    'Type': 'QZL',
                    'LoadStart': '114.',
                    'LoadEnd': '114.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'})]}),
        'BarLoad_BGT': Munch({
            'staven': [Munch({
                'ID': '55',
                'BarID': '1',
                'Type': 'QZL',
                'LoadStart': '68.',
                'LoadEnd': '68.',
                'DistanceStart': '0.',
                'DistanceEnd': '0.'}), Munch({
                'ID': '56',
                'BarID': '2',
                'Type': 'QZL',
                'LoadStart': '68.',
                'LoadEnd': '68.',
                'DistanceStart': '0.',
                'DistanceEnd': '0.'}),
                Munch({
                    'ID': '57',
                    'BarID': '3',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '58',
                    'BarID': '4',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '59',
                    'BarID': '5',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '60',
                    'BarID': '6',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '61',
                    'BarID': '7',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '62',
                    'BarID': '8',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '63',
                    'BarID': '9',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '64',
                    'BarID': '10',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '65',
                    'BarID': '11',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '66',
                    'BarID': '12',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '67',
                    'BarID': '13',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '68',
                    'BarID': '14',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '69',
                    'BarID': '15',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '70',
                    'BarID': '16',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '71',
                    'BarID': '17',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '72',
                    'BarID': '18',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '73',
                    'BarID': '19',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '74',
                    'BarID': '20',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '75',
                    'BarID': '21',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '76',
                    'BarID': '22',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '77',
                    'BarID': '23',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '78',
                    'BarID': '24',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '79',
                    'BarID': '25',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '80',
                    'BarID': '26',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '81',
                    'BarID': '27',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '82',
                    'BarID': '28',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '83',
                    'BarID': '29',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '84',
                    'BarID': '30',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '85',
                    'BarID': '31',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '86',
                    'BarID': '32',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '87',
                    'BarID': '33',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '88',
                    'BarID': '34',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '89',
                    'BarID': '35',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '90',
                    'BarID': '36',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '91',
                    'BarID': '37',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '92',
                    'BarID': '38',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '93',
                    'BarID': '39',
                    'Type': 'QZL',
                    'LoadStart': '68.',
                    'LoadEnd': '68.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '94',
                    'BarID': '40',
                    'Type': 'QZL',
                    'LoadStart': '87.',
                    'LoadEnd': '87.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '95',
                    'BarID': '41',
                    'Type': 'QZL',
                    'LoadStart': '87.',
                    'LoadEnd': '87.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '96',
                    'BarID': '42',
                    'Type': 'QZL',
                    'LoadStart': '87.',
                    'LoadEnd': '87.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '97',
                    'BarID': '43',
                    'Type': 'QZL',
                    'LoadStart': '87.',
                    'LoadEnd': '87.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '98',
                    'BarID': '44',
                    'Type': 'QZL',
                    'LoadStart': '87.',
                    'LoadEnd': '87.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '99',
                    'BarID': '45',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '100',
                    'BarID': '46',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '101',
                    'BarID': '47',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '102',
                    'BarID': '48',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '103',
                    'BarID': '49',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '104',
                    'BarID': '50',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '105',
                    'BarID': '51',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '106',
                    'BarID': '52',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}),
                Munch({
                    'ID': '107',
                    'BarID': '53',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'}), Munch({
                    'ID': '108',
                    'BarID': '54',
                    'Type': 'QZL',
                    'LoadStart': '73.',
                    'LoadEnd': '73.',
                    'DistanceStart': '0.',
                    'DistanceEnd': '0.'})]}),
        'LoadCases': Munch({
            'loads': [Munch({
                'ID': '1',
                'description': '',
                'LoadCaseType': 'Permanent'}),
                Munch({
                    'ID': '2',
                    'description': '',
                    'LoadCaseType': 'Permanent'})]})}),
    'calculation': Munch({
        'UGT': True,
        'BGT': True,
        'calamity': [],
        'temperature': 30,
        'displacement': 50,
        'thickness_plate': 20,
        'hoh': 1,
        'excentricity': 30,
        'k_value_sheetpile': 10000}),
    'm_factor': '1/16',
    'downloads': Munch({
        'laden': Munch({
            'bgt': 'point_load_0'})}),
    'visualization': Munch({
        'geometry': Munch({
            'show_labels': True,
            'show_nodes': True,
            'show_fixedsupports': True,
            'show_springs': True})}),
    'name': 'H22.0225-B Stempelframe(2).xml',
    'filename': 'storage/dev-ymacken-viktor-ai/197c00b1-2689-441d-9c07-c39f76211498'})