RWW_DICT = {
    "STRAMIENLIJNEN": {
        "skip_rows": 3,
        "columns": ["Nr.", "Omschrijving", "X", "Z-min", "Z-max"],
    },
    "NIVEAUS": {"skip_rows": 3, "columns": ["Nr.", "Z", "X-min", "X-max"]},
    "MATERIALEN": {
        "skip_rows": 3,
        "columns": [
            "Mt",
            "Omschrijving",
            "E-modulus[N/mm2]",
            "S.G.",
            "Pois.",
            "Uitz. coëff",
        ],
    },
    "PROFIELEN [mm]": {
        "skip_rows": 3,
        "columns": [
            "Prof.",
            "Omschrijving",
            "Materiaal",
            "Oppervlak",
            "Traagheid",
            "Vormf.",
        ],
    },
    "PROFIELEN vervolg [mm]": {
        "skip_rows": 3,
        "columns": [
            "Prof.",
            "Staaftype",
            "Breedte",
            "Hoogte",
            "e",
            "Type",
            "b1",
            "h1",
            "b2",
            "h2",
        ],
    },
    "KNOPEN": {"skip_rows": 3, "columns": ["Knoop", "X", "Z", "Knoop", "X", "Z"]},
    "STAVEN": {
        "skip_rows": 3,
        "columns": [
            "St.",
            "ki",
            "kj",
            "Profiel",
            "Aansl.i",
            "Aansl.j",
            "Lengte",
            "Opm.",
        ],
    },
    "VEREN": {
        "skip_rows": 4,
        "columns": [
            "Veer",
            "Knoop",
            "Richting",
            "Hoek",
            "Veerwaarde",
            "Type",
            "Ondergrens",
            "Bovengrens",
        ],
    },
    "VASTE STEUNPUNTEN": {
        "skip_rows": 3,
        "columns": ["Nr.", "Knoop", "Kode XZR 1-vast 0=vrij", "Hoek"],
    },
    "BEDDINGEN": {
        "skip_rows": 3,
        "columns": ["Nr.", "Staven", "Bedding", "Breedte[mm]", "Zijde"],
    },
    "STAAFBELASTINGEN   B.G:1 UGT": {
        "skip_rows": 3,
        "columns": [
            "Last",
            "Staaf",
            "Type",
            "q1/p/m",
            "q2",
            "A",
            "B",
            "psi",
            "psi-t",
            "Opm",
        ],
    },
    "STAAFKRACHTEN  Fundamentele combinatie": {
        "skip_rows": 3,
        "columns": ["St.", "Kn. Pos.", "NXi/NXj", "DZi/DZj", "MYi/MYj"],
    },
    "STAAFKRACHTEN  B.C:1 Sterkte": {
        "skip_rows": 3,
        "columns": ["St.", "Kn. Pos.", "NXi/NXj", "DZi/DZj", "MYi/MYj"],
    },
    "STAAFBELASTINGEN   B.G:2 BGT": {
        "skip_rows": 3,
        "columns": [
            "Last",
            "Staaf",
            "Type",
            "q1/p/m",
            "q2",
            "A",
            "B",
            "psi",
            "psi-t",
            "Opm",
        ],
    },
    "STAAFKRACHTEN  B.C:2 Vervorming": {
        "skip_rows": 3,
        "columns": ["St.", "Kn. Pos.", "NXi/NXj", "DZi/DZj", "MYi/MYj"],
    },
    "TUSSENPUNTEN VERPLAATSINGEN  B.C:2 Vervorming": {
        "skip_rows": 3,
        "columns": [
            "St.",
            "Kn. Pos. ",
            "Verpl-X_gl",
            "Verpl_z_gl",
            "Verpl-X_lo",
            "Verpl_z_lo",
            "Rotatie",
            "Grondspan.",
        ],
    },
    "BELASTINGCOMBINATIES": {"skip_rows": 3, "columns": ["BC", "Type", "Waarde", "A"]},
}

uitzet_coëff = 1.2 * 10**-5  # 1/C°
χLT = 1  # kipreductiefactor volgens 6.3.2 > 6.3.3
imperfectie_f_a0 = 0.13  # [-] imperfectiefactor α  voor buisprofiel warmvervaardigd: Tabel 6.1 NEN-EN 1993-1-1  ***** NAGAAN OF DIT NOG MOET WORDEN GEAUTOMATISEERD
imperfectie_f_a = 0.21
Cmy = 0.95  # equivalente momentenverdelingsfactor (rekening houdend met het niet-gelijkmatig momentverloop)
M0 = 1  # partiële factor voor de weerstand van dwarsdoorsneden
M1 = 1  # partiële factor voor de weerstand mbt instabiliteit
M2 = 1.25  # partiële factor voor de weerstand op trek belaste doorsnede
γstempel_UGT = 1.25
γeg_UGT = 1.2
γQ_UGT = 1.5
γtemp_UGT = 1.25
γm_gording_UGT = 1.1
γstempel_BGT = 1
γeg_BGT = 1
γQ_BGT = 1
γtemp_BGT = 1
γm_gording_BGT = 1
soortgelijk_gewicht = 7850  # kg/m3
lijnlast = 1  # kN/m
uc_uitval = 0
point_load_calamity_value = 100  # kN

dict_sterkte_fu = {235: 360, 275: 430, 355: 510, 440: 550}

stamp_failure = "B121/5"

YOUNG_MODULUS_STEEL = 210000

columns_calculations_stamps = [
    "St.",
    "ki",
    "kj",
    "Prof.",
    "prof_id",
    "bu",
    "wa",
    "lengte",
    "fy",
    "fu",
    "Wpl",
    "Sterkteklasse",
    "Wel",
    "I",
    "A",
    "Av",
    "G",
    "E",
    "d/t/e",
    "drsn. kl.",
    "NXi/NXj_UGT",
    "NXi/NXj_UGT_γ",
    "NXi/NXj_UGT_trek",
    "NXi/NXj_UGT_druk",
    "NXi/NXj_BGT",
    "NXi/NXj_BGT_trek",
    "NXi/NXj_BGT_druk",
    "Meg",
    "Mrep_lijn_UGT",
    "Mrep_punt_UGT",
    "vervorming",
    "Excentrisch",
    "M2e orde_UGT",
    "Mrep,excen_UGT",
    "Mrep,excen_BGT",
    "M2e orde_BGT",
    "Vrep,eg",
    "Vrep,lijn",
    "Vrep,punt_UGT",
    "Vrep,punt_BGT",
    "Nrep_UGT",
    "Nrep_BGT",
    "NT,rep",
    "max_lijn_punt_Med_UGT",
    "max_lijn_punt_Ved_UGT",
    "max_lijn_punt_Med_BGT",
    "max_lijn_punt_Ved_BGT",
    "MEd,midden_UGT",
    "MEd,midden_BGT",
    "VEd,kop_UGT",
    "VEd,kop_BGT",
    "VEd,midden_UGT",
    "VEd,midden_BGT",
    "NEd,druk_UGT",
    "NEd,druk_BGT",
    "NRd",
    "NEd_UGT",
    "uc_NEd_UGT",
    "NEd_BGT",
    "uc_NEd_BGT",
    "Wy-y",
    "MRd",
    "MEd_UGT",
    "uc_MEd_UGT",
    "MEd_BGT",
    "uc_MEd_BGT",
    "Mc,Rd_UGT",
    "Mc,Rd_BGT",
    "u.c. Med/Mc,Rd_UGT",
    "u.c. Med/Mc,Rd_BGT",
    "Vc,Rd",
    "VEd_UGT",
    "uc_VEd_UGT",
    "VEd_BGT",
    "uc_VEd_BGT",
    "uc_MEd_NEd_UGT_1",
    "uc_MEd_NEd_UGT_2",
    "uc_MEd_NEd_BGT_1",
    "uc_MEd_NEd_BGT_2",
    "reductie_UGT",
    "reductie_BGT",
    "q_UGT",
    "q_BGT",
    "NV,Rd_UGT",
    "NV,Rd_BGT",
    "MV,Rd_UGT",
    "MV,Rd_BGT",
    "uc_MEd_MV,Rd_UGT_1",
    "uc_MEd_MV,Rd_BGT_1",
    "uc_MEd_MV,Rd_UGT_2",
    "uc_MEd_MV,Rd_BGT_2",
    "Ncr",
    "imperfectie_f",
    "λrel",
    "Φ",
    "χ",
    "uc_χ",
    "Nb,Rd",
    "uc_NEd_Nb,Rd_UGT",
    "uc_NEd_Nb,Rd_BGT",
    "kyy_1en2_1_UGT",
    "kyy_1en2_2_UGT",
    "uc_kyy_1en2_UGT",
    "kyy_3en4_1_UGT",
    "kyy_3en4_2_UGT",
    "uc_kyy_3en4_UGT",
    "kyy_UGT",
    "uc_kyy_UGT",
    "uc_kzy_UGT",
    "kyy_1en2_1_BGT",
    "kyy_1en2_2_BGT",
    "uc_kyy_1en2_BGT",
    "kyy_3en4_1_BGT",
    "kyy_3en4_2_BGT",
    "uc_kyy_3en4_BGT",
    "kyy_BGT",
    "uc_kyy_BGT",
    "uc_kzy_BGT",
    "uc_NEd_kyy_My,Ed_UGT",
    "uc_NEd_kzy_My,Ed_UGT",
    "uc_NEd_kyy_My,Ed_BGT",
    "uc_NEd_kzy_My,Ed_BGT",
    "Naam",
    "aan/uit",
]

columns_calculations_purlins = [
    "St.",
    "ki",
    "ki_x",
    "ki_z",
    "ki_def",
    "kj",
    "kj_x",
    "kj_z",
    "kj_def",
    "Aansl.i",
    "Aansl.j",
    "Lengte",
    "Profiel",
    "ID_sterkte",
    "Profiel_",
    "Profiel_naam",
    "n_profiles",
    "profiel_naam",
    "BGT_stempelkracht",
    "UGT_stempelkracht",
    "Sterkteklasse",
    "Kn. Pos.",
    "N_druk",
    "N_trek",
    "NXi/NXj",
    "DZi/DZj",
    "hoh",
    "m_factor",
    "Naam",
    "MYi/MYj",
    "N_BGT",
    "M_BGT",
    "h",
    "b",
    "A",
    "Wy_el",
    "Wy_pl",
    "Wz_el",
    "Wz_pl",
    "tw",
    "tf",
    "r",
    "Iy",
    "ε",
    "λ1",
    "lijf c/t/ε",
    "flens c/t/ε",
    "MR_rep",
    "drsn. kl. lijf_buiging",
    "Wyy",
    "MRd",
    "uc_MR_rep_ME_rep",
    "NEd_trek",
    "NRd",
    "uc_NEd_trek_Nt_Rd",
    "NEd_druk",
    "uc_NEd_druk_Nc_Rd",
    "MEd",
    "uc_MEd_MRd",
    "VEd",
    "drsn. kl. lijf_druk",
    "Av",
    "hw",
    "Aw",
    "A_Vc_Rd,",
    "Vc_Rd",
    "uc_VEd_Vc_Rd",
    "uc_controle_lijf_zonder_dwarsverstijvers",
    "ρ",
    "My_V_Rd",
    "uc_My_V_Rd_check",
    "uc_MEd_My_V_Rd",
    "a",
    "uc_a",
    "imperfectie",
    "imperfectie_klasse_1",
    "imperfectie_klasse_2",
    "imperfectie_klasse_",
    "klasse_1",
    "klasse_2",
    "drsn. kl. druk_buiging",
    "MNy_Rd",
    "uc_MEd_MNy_Rd",
    "uc_MEd_MNy_Rd_kl_3en4",
    "uc_MEd_VEd_klasse_raw",
    "uc_MEd_VEd_klasse",
    "uc_reductie_check",
    "ρ_",
    "NVz_Rd",
    "a1_",
    "a1",
    "a2",
    "MVy_Rd",
    "uc_My_Ed_My_Vd_NEd_NVz_Rd_1en2",
    "uc_My_Ed_My_Vd_NEd_NVz_Rd",
    "reductie_check",
    "max_NEd",
    "check_a",
    "My_V_Rd_check",
    "controle_lijf_zonder_dwarsverstijvers",
    "Iz",
    "G",
    "A_Vc_Rd",
    "MNt_Rd",
    "L_BGT_wall",
]

columns_results_stamps_UGT = [
    "St.",
    "wa",
    "Naam",
    "Prof.",
    "lengte",
    "fy",
    "NXi/NXj_UGT_druk",
    "uc_NEd_UGT",
    "uc_MEd_UGT",
    "uc_VEd_UGT",
    "uc_MEd_NEd_UGT_1",
    "uc_MEd_NEd_UGT_2",
    "uc_MEd_MV,Rd_UGT_1",
    "uc_MEd_MV,Rd_UGT_2",
    "uc_χ",
    "uc_NEd_Nb,Rd_UGT",
    "uc_kyy_1en2_UGT",
    "uc_kyy_UGT",
    "uc_kyy_3en4_UGT",
    "uc_kzy_UGT",
    "uc_NEd_kyy_My,Ed_UGT",
    "uc_NEd_kzy_My,Ed_UGT",
    "toets_maatgevend",
    "uc_maatgevend",
    "result",
]

columns_results_stamps_BGT = [
    "Naam",
    "St.",
    "Prof.",
    "lengte",
    "fy",
    "NXi/NXj_BGT_druk",
    "uc_NEd_BGT",
    "uc_MEd_BGT",
    "uc_VEd_BGT",
    "uc_MEd_NEd_BGT_1",
    "uc_MEd_NEd_BGT_2",
    "uc_MEd_MV,Rd_BGT_1",
    "uc_MEd_MV,Rd_BGT_2",
    "uc_χ",
    "uc_NEd_Nb,Rd_BGT",
    "uc_kyy_1en2_BGT",
    "uc_kyy_BGT",
    "uc_kyy_3en4_BGT",
    "uc_kzy_BGT",
    "uc_NEd_kyy_My,Ed_BGT",
    "uc_NEd_kzy_My,Ed_BGT",
    "toets_maatgevend",
    "uc_maatgevend",
    "result",
]

columns_results_purlins = [
    "Naam",
    "St.",
    "profiel_naam",
    "n_profiles",
    "Sterkteklasse",
    "Lengte",
    "N_trek",
    "N_druk",
    "DZi/DZj",
    "MYi/MYj",
    "hoh",
    "m_factor",
    "uc_MR_rep_ME_rep",
    "uc_NEd_trek_Nt_Rd",
    "uc_NEd_druk_Nc_Rd",
    "uc_MEd_MRd",
    "uc_VEd_Vc_Rd",
    "controle_lijf_zonder_dwarsverstijvers",
    "uc_controle_lijf_zonder_dwarsverstijvers",
    "uc_My_V_Rd_check",
    "uc_MEd_My_V_Rd",
    "uc_a",
    "uc_MEd_VEd_klasse",
    "L_BGT_wall",
    "uc_My_Ed_My_Vd_NEd_NVz_Rd",
    "uc_maatgevend_UGT",
    "uc_maatgevend",
    "result",
]

columns_calculations_preface_forces = [
    "g_St.",
    "g_ki",
    "g_ki_x",
    "g_ki_z",
    "g_kj",
    "g_kj_x",
    "g_kj_z",
    "s_aansl_St.",
    "s_ki",
    "s_ki_x",
    "s_ki_z",
    "s_kj",
    "s_kj_x",
    "s_kj_z",
    "Kn. Pos.",
    "x_A",
    "z_A",
    "x_B",
    "z_B",
    "x_C",
    "z_C",
    "[°]",
    "s_A",
    "s_d_inw",
    "s_I",
    "s_Wel",
    "s_Wpl",
    "s_fy",
    "s_fu",
    "s_E",
    "s_ε",
    "s_λ1",
    "h",
    "b",
    "g_n",
    "A",
    "Wy_el",
    "Wy_pl",
    "hw",
    "tw",
    "tf",
    "r",
    "g_fy",
    "g_fu",
    "g_ε",
    "g_λ1",
    "s_NEd_druk_UGT",
    "s_NEd_druk_BGT",
    "g_NEd_trek_UGT",
    "g_NEd_trek_BGT",
    "g_NEd_druk_UGT",
    "g_NEd_druk_BGT",
    "g_max_N_UGT",
    "g_max_N_BGT",
    "g_MYi/MYj_UGT",
    "g_MYi/MYj_BGT",
    "thickness_plate",
    "t_drukschot",
    "s_FEd_UGT",
    "s_FEd_BGT",
    "s_beff",
    "g_σfEd_UGT",
    "g_σfEd_BGT",
    "g_bf",
    "g_c",
    "g_d1_UGT",
    "g_d1_BGT",
    "F1Rd_UGT",
    "F1Rd_BGT",
    "g_uc_FEd_F1Rd_UGT",
    "g_uc_FEd_F1Rd_BGT",
    "c/(h-2t*tf)",
    "F2Rd",
    "uc_FEd_F2Rd_UGT",
    "uc_FEd_F2Rd_BGT",
    "uc_FEd_F2RD_MyEd_MyRd_UGT",
    "uc_FEd_F2RD_MyEd_MyRd_BGT",
    "g_beff",
    "Fcr",
    "g_λrel",
    "uc_FEd_Fcr_UGT",
    "uc_FEd_Fcr_BGT",
]

columns_results_preface_forces = [
    "Kn. Pos.",
    "St.",
    "g_profiel_naam",
    "n_profiles",
    "g_Sterkteklasse",
    "s_profiel_naam",
    "s_Sterkteklasse",
    "Hoek",
    "thickness_plate",
    "t_drukschot",
    "FEd_UGT",
    "NXi/NXj_UGT",
    "MYi/MYj_UGT",
    "FEd_BGT",
    "NXi/NXj_BGT",
    "MYi/MYj_BGT",
    "s_uc_FEd_FRd_UGT",
    "s_uc_FEd_FRd_BGT",
    "g_uc_FEd_F1Rd_UGT",
    "g_uc_FEd_F1Rd_BGT",
    "uc_FEd_F2Rd_UGT",
    "uc_FEd_F2Rd_BGT",
    "uc_FEd_F2RD_MyEd_MyRd_UGT",
    "uc_FEd_F2RD_MyEd_MyRd_BGT",
    "uc_FEd_Fcr_UGT",
    "uc_FEd_Fcr_BGT",
    "check_FEd_Fcr_UGT",
    "check_FEd_Fcr_BGT",
    "uc_g_χ",
    "uc_FEd_FbRD_UGT",
    "uc_FEd_FbRD_BGT",
    "uc_maatgevend_UGT",
    "uc_maatgevend_U",
    "uc_maatgevend_BGT",
    "uc_maatgevend_B",
]
